name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-18.04 ,windows-latest, macos-latest]
        qt: [5.15.2]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Qt ${{ matrix.qt }} on ${{ matrix.os }}
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
        modules: qtcharts
    - name: Set up MSVC Developer Command Prompt (Windows)
      if: matrix.os == 'windows-latest'
      uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        arch: x64

    - name: Build (Linux)
      if: matrix.os == 'ubuntu-18.04'
      run: |
        qmake -config release
        make
        mkdir -p target/distribution/usr/bin target/distribution/usr/lib target/distribution/usr/share/aplications
        mv target/release/burnback-qt target/distribution/usr/bin/
        mv ./burnback-qt.desktop target/distribution/usr/share/applications/
        cd target
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage distribution/usr/share/applications/burnback-qt.desktop -qmldir=../src-qml -bundle-non-qt-libs

    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        qmake -config release
        nmake
        mkdir target\distribution
        mv target/release/burnback-qt.exe target/distribution/
        cd target/distribution
        windeployqt.exe burnback-qt.exe --qmldir=../../src-qml
      shell: cmd

    - name: Build (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        qmake -config release
        make
        mkdir target/distribution
        mv target/release/burnback-qt.app target/distribution/
        cd target/distribution
        macdeployqt burnback-qt.app -qmldir=../../src-qml

    - name: Zipping files
      uses: vimtor/action-zip@v1.1
      with:
        files: target/distribution/
        dest: burnback-qt-${{ matrix.os }}.zip

    - name: Uploading to release
      uses: ncipollo/release-action@v1
      with:
        artifacts: burnback-qt-${{ matrix.os }}.zip
        allowUpdates: true
        makeLatest: true
