name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        qt: [5.15.2]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Qt ${{ matrix.qt }} on ${{ matrix.os }}
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}
        modules: qtcharts
    - name: Install MSVC Build Tools
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: make release
    - name: Upload Release Binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: Linux Release Binary
        path: target/release/burnback-qt
    - name: Upload Release Binary (Mac)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: Mac Release Binary
        path: target/release/burnback-qt.app
    - name: Upload Release Binary (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: Windows Release Binary
        path: target/release/burnback-qt.exe

